"""initial tables - patients, medications, triage, symptom checks

Revision ID: 49fa91218c46
Revises: 
Create Date: 2026-03-24 18:35:44.468330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49fa91218c46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('allergies', sa.String(length=1000), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_full_name'), 'patients', ['full_name'], unique=False)
    op.create_table('medication_reminders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('medication_name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('times', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('instructions', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_reminders_patient_id'), 'medication_reminders', ['patient_id'], unique=False)
    op.create_table('symptom_check_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('symptoms', sa.String(length=2000), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('conditions_found', sa.String(length=2000), nullable=False),
    sa.Column('recommended_action', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_check_records_patient_id'), 'symptom_check_records', ['patient_id'], unique=False)
    op.create_table('triage_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('chief_complaint', sa.String(length=1000), nullable=False),
    sa.Column('symptoms', sa.String(length=2000), nullable=False),
    sa.Column('symptom_duration', sa.String(length=200), nullable=False),
    sa.Column('pain_scale', sa.Integer(), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=False),
    sa.Column('bp_systolic', sa.Integer(), nullable=False),
    sa.Column('bp_diastolic', sa.Integer(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('respiratory_rate', sa.Integer(), nullable=False),
    sa.Column('oxygen_saturation', sa.Integer(), nullable=False),
    sa.Column('priority_level', sa.Integer(), nullable=False),
    sa.Column('priority_label', sa.String(length=50), nullable=False),
    sa.Column('recommended_action', sa.String(length=500), nullable=False),
    sa.Column('flags', sa.String(length=2000), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_records_patient_id'), 'triage_records', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_records_patient_id'), table_name='triage_records')
    op.drop_table('triage_records')
    op.drop_index(op.f('ix_symptom_check_records_patient_id'), table_name='symptom_check_records')
    op.drop_table('symptom_check_records')
    op.drop_index(op.f('ix_medication_reminders_patient_id'), table_name='medication_reminders')
    op.drop_table('medication_reminders')
    op.drop_index(op.f('ix_patients_full_name'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
