"""add status column to triage_records

Revision ID: 602366bc2164
Revises: f522cfbee7d9
Create Date: 2026-03-24 19:00:25.118407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602366bc2164'
down_revision: Union[str, None] = 'f522cfbee7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triage_records', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_triage_records_status'), 'triage_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_records_status'), table_name='triage_records')
    op.drop_column('triage_records', 'status')
    # ### end Alembic commands ###
