"""convert varchar json fields to native JSON columns

Revision ID: 7501aeb0465b
Revises: 602366bc2164
Create Date: 2026-03-24 19:49:40.454263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7501aeb0465b'
down_revision: Union[str, None] = '602366bc2164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # PostgreSQL requires USING clause to cast VARCHAR to JSON
    op.execute('ALTER TABLE medication_reminders ALTER COLUMN times TYPE JSON USING times::json')
    op.execute('ALTER TABLE symptom_check_records ALTER COLUMN symptoms TYPE JSON USING symptoms::json')
    op.execute('ALTER TABLE symptom_check_records ALTER COLUMN conditions_found TYPE JSON USING conditions_found::json')
    op.execute('ALTER TABLE triage_records ALTER COLUMN symptoms TYPE JSON USING symptoms::json')
    op.execute('ALTER TABLE triage_records ALTER COLUMN flags TYPE JSON USING flags::json')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('triage_records', 'flags',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
    op.alter_column('triage_records', 'symptoms',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
    op.alter_column('symptom_check_records', 'conditions_found',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
    op.alter_column('symptom_check_records', 'symptoms',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
    op.alter_column('medication_reminders', 'times',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
